# Generated by Django 4.2.7 on 2023-12-01 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identificador del registro', primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
