# Generated by Django 4.2.7 on 2023-12-04 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Identificador del registro', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='Activo✅ / Inactivo ❌ ', verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha en la cuál se creó el registro', verbose_name='Fecha creación')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación del registro', verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, help_text='Fecha de desactivación del registro.', verbose_name='Fecha de eliminación')),
                ('description', models.CharField(help_text='Motivo o descripción de estas elecciones', max_length=200, verbose_name='Descripción')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora a la cual dará inicio el conteo de votos.', verbose_name='Fecha y hora de inicio')),
                ('fecha_final', models.DateTimeField(help_text='Fecha y hora que dará finalizado el conteo de votos.', verbose_name='Fecha y hora de finalización')),
                ('observation', models.TextField(blank=True, help_text='Indique alguna observación o notas acerca de estas elecciones', null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Eleccion',
                'verbose_name_plural': 'Elecciones',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Identificador del registro', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='Activo✅ / Inactivo ❌ ', verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha en la cuál se creó el registro', verbose_name='Fecha creación')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación del registro', verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, help_text='Fecha de desactivación del registro.', verbose_name='Fecha de eliminación')),
                ('acciones', models.BigIntegerField(help_text='El votante contaba con esta cantidad de acciones', verbose_name='Acciones del voto')),
                ('tipo', models.CharField(choices=[('N', 'Voto nulo'), ('V', 'Voto normal')], help_text='Indica si el voto es Normal o es voto Nulo', max_length=1, verbose_name='Tipo de voto')),
                ('candidato', models.ForeignKey(blank=True, help_text='Este voto es para este candidato, si no hay candidato, es voto nulo', null=True, on_delete=django.db.models.deletion.RESTRICT, to='candidatos.candidato', verbose_name='Candidato votado')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('eleccion', models.ForeignKey(help_text='Este voto está registrado en estas elecciones', on_delete=django.db.models.deletion.RESTRICT, to='elecciones.eleccion', verbose_name='Voto en esta Elección')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalVoto',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Identificador del registro', verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='Activo✅ / Inactivo ❌ ', verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Fecha en la cuál se creó el registro', verbose_name='Fecha creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, help_text='Fecha de última modificación del registro', verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, help_text='Fecha de desactivación del registro.', verbose_name='Fecha de eliminación')),
                ('acciones', models.BigIntegerField(help_text='El votante contaba con esta cantidad de acciones', verbose_name='Acciones del voto')),
                ('tipo', models.CharField(choices=[('N', 'Voto nulo'), ('V', 'Voto normal')], help_text='Indica si el voto es Normal o es voto Nulo', max_length=1, verbose_name='Tipo de voto')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('candidato', models.ForeignKey(blank=True, db_constraint=False, help_text='Este voto es para este candidato, si no hay candidato, es voto nulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='candidatos.candidato', verbose_name='Candidato votado')),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('eleccion', models.ForeignKey(blank=True, db_constraint=False, help_text='Este voto está registrado en estas elecciones', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='elecciones.eleccion', verbose_name='Voto en esta Elección')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Voto',
                'verbose_name_plural': 'historical Votos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalElecciones_Candidato',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Identificador del registro', verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='Activo✅ / Inactivo ❌ ', verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Fecha en la cuál se creó el registro', verbose_name='Fecha creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, help_text='Fecha de última modificación del registro', verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, help_text='Fecha de desactivación del registro.', verbose_name='Fecha de eliminación')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('candidato', models.ForeignKey(blank=True, db_constraint=False, help_text='Este voto es para este candidato, si no hay candidato, es voto nulo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='candidatos.candidato', verbose_name='Candidato votado')),
                ('cargo', models.ForeignKey(blank=True, db_constraint=False, help_text='Cargo que desempeñará el candidato en las elecciones', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='candidatos.cargo', verbose_name='Cargo')),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('eleccion', models.ForeignKey(blank=True, db_constraint=False, help_text='Este voto está registrado en estas elecciones', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='elecciones.eleccion', verbose_name='Voto en esta Elección')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical BaseModel',
                'verbose_name_plural': 'historical BaseModels',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalEleccion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Identificador del registro', verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='Activo✅ / Inactivo ❌ ', verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Fecha en la cuál se creó el registro', verbose_name='Fecha creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, help_text='Fecha de última modificación del registro', verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, help_text='Fecha de desactivación del registro.', verbose_name='Fecha de eliminación')),
                ('description', models.CharField(help_text='Motivo o descripción de estas elecciones', max_length=200, verbose_name='Descripción')),
                ('fecha_inicio', models.DateTimeField(help_text='Fecha y hora a la cual dará inicio el conteo de votos.', verbose_name='Fecha y hora de inicio')),
                ('fecha_final', models.DateTimeField(help_text='Fecha y hora que dará finalizado el conteo de votos.', verbose_name='Fecha y hora de finalización')),
                ('observation', models.TextField(blank=True, help_text='Indique alguna observación o notas acerca de estas elecciones', null=True, verbose_name='Observaciones')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Eleccion',
                'verbose_name_plural': 'historical Elecciones',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Elecciones_Candidato',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Identificador del registro', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='Activo✅ / Inactivo ❌ ', verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha en la cuál se creó el registro', verbose_name='Fecha creación')),
                ('modified_date', models.DateTimeField(auto_now=True, help_text='Fecha de última modificación del registro', verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, help_text='Fecha de desactivación del registro.', verbose_name='Fecha de eliminación')),
                ('candidato', models.ForeignKey(help_text='Este voto es para este candidato, si no hay candidato, es voto nulo', on_delete=django.db.models.deletion.RESTRICT, to='candidatos.candidato', verbose_name='Candidato votado')),
                ('cargo', models.ForeignKey(help_text='Cargo que desempeñará el candidato en las elecciones', on_delete=django.db.models.deletion.RESTRICT, to='candidatos.cargo', verbose_name='Cargo')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('eleccion', models.ForeignKey(help_text='Este voto está registrado en estas elecciones', on_delete=django.db.models.deletion.RESTRICT, to='elecciones.eleccion', verbose_name='Voto en esta Elección')),
            ],
            options={
                'verbose_name': 'BaseModel',
                'verbose_name_plural': 'BaseModels',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eleccion',
            name='candidatos',
            field=models.ManyToManyField(help_text='Participantes como candidatos.', through='elecciones.Elecciones_Candidato', to='candidatos.candidato', verbose_name='Candidatos'),
        ),
        migrations.AddField(
            model_name='eleccion',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='Último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
        ),
    ]
