# Generated by Django 4.2.7 on 2023-12-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='max_votos',
            field=models.IntegerField(default=1, help_text='El número máximo de votos por cargo en unas elecciones', verbose_name='Máximo de voto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcargo',
            name='max_votos',
            field=models.IntegerField(default=1, help_text='El número máximo de votos por cargo en unas elecciones', verbose_name='Máximo de voto'),
            preserve_default=False,
        ),
    ]
